# Run: jekyll serve --config _config.yml,_config_dev.yml for local development

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mark Omwansa
title_html: <b>mark</b>omwansa
email: m.omwansa@gmail.com
shortbio: >-
  I currently reside in the United States and enjoy learning new and interesting
  things.
pitch: technology, engineering etc
description: >- # this means to ignore newlines until "baseurl:"
  Blog about things in Technology, Engineering, Art, and other things that
  peak my interest etc.
nb_posts_page: 10

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mrkmwns
github_username:  ntntnlstdnt
linkedin_username: markomwansa


# Build settings
markdown: kramdown
theme: academic
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
